---
swagger: "2.0"
info:
  version: "1.0"
  description: "Customer API"
  title: "Custmer details"
  contact:
    email: "ravilan1@in.ibm.com"
host: "127.0.0.1:9579"
basePath: "/spi/v1"
schemes:
- "http"
- "https"
paths:
  /getCustomerId/{id}:
    get:
      description: "Get customer details based on customerid"
      operationId: "getCustomerId"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        required: true
        type: "string"
        in: "path"
      - name: "name"
        in: "query"
        type: "string"
        required: true
